### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by vladimirshefer** [nikolay-govorov/snake#1]
I followed the installation guide in README.md and nothing happened!

OS: Linux Ubuntu 18.04
Build tool: Gradle 6.3
Java: 11-open

**Comment by mrdimidium** [comment]
Hi. Thank you for your contribution, sorry that you had to face this.

The fact is that a few drinks distracted me from this project. But given your interest, I've unpacked a case of ginger beer and will probably finish it soon

**Comment by mrdimidium** [comment]
If you are currently in St. Petersburg, we can discuss this in more detail over a couple of Beers.

**Comment by mrdimidium** [comment]
Done, specially for you: [nikolay-govorov.github.io/snake/](https://nikolay-govorov.github.io/snake/)
